### PR TITLE
bazel: Dump input of non-fatal UBSan findings

### PR DESCRIPTION
**Pull request by adombeck**
Based on CLI-664-bazel-support-ubsan

### CODE REVIEW

**Review by fmeum — APPROVED** [review]

**Comment by fmeum** [comment]
@adombeck I added a new test and some additional fixes. Could you take another look?

**Comment by adombeck** [comment]
> @adombeck I added a new test and some additional fixes. Could you take another look?

LGTM. Not entirely sure about the `local_repository` in the example, because users might want to use the example projects as the basis for their own projects, but the commented out `git_repository` should help in those cases.

**Comment by fmeum** [comment]
@adombeck I set up https://github.com/CodeIntelligenceTesting/cifuzz-bazel and moved rather than copied the Bazel-only bits to it. I had to copy some files and we should investigate how we could automate that in the future.

**Comment by adombeck** [comment]
Out of curiosity: I see that you renamed the file made available via bazel from `dumper.c` to `dumper.cpp` - does that make any difference?

**Comment by fmeum** [comment]
> Out of curiosity: I see that you renamed the file made available via bazel from `dumper.c` to `dumper.cpp` - does that make any difference?

I did that already in the version of this PR that still had the `BUILD.bazel` file in it explicitly. The reason is subtle, but explained here: https://github.com/CodeIntelligenceTesting/cifuzz-bazel/blob/1ccb0bb7f27864626f668cca6d6e87776e6f87bd/BUILD.bazel#L27-L32

**Comment by adombeck** [comment]
> Out of curiosity: I see that you renamed the file made available via bazel from dumper.c to dumper.cpp - does that make any difference?

Ah, I see now that it's explained in a comment in the `BUILD.bazel`?

**Comment by adombeck** [comment]
LGTM

**Pull request merged**
