### PR TITLE
added architecture check when target is Darwin

### PR DESCRIPTION
**Pull request by MarkusZoppelt**
Added an architecture check in `Makefile` that checks Darwin processor type:

```make
ifeq ($(UNAME_S),Darwin)
    current_os = darwin
    UNAME_P := $(shell uname -p)
endif
```
[...]
```make
ifeq ($(UNAME_P), arm)
    env GOOS=darwin GOARCH=arm64 go build -o $(binary_base_path)_darwin cmd/cifuzz/main.go
else
    env GOOS=darwin GOARCH=amd64 go build -o $(binary_base_path)_darwin cmd/cifuzz/main.go
endif
```

### CODE REVIEW

**Comment by adombeck** [comment]
Code looks good to me. @HenrichN I think you're the only dev with an M1 Mac, could you check that `make build` runs without errors and that you can execute the `build/bin/cifuzz_darwin` produced by the build?

**Comment by HenrichN** [comment]
Works for me!
```
➜  cifuzz git:(make-m1-mac) uname -m
arm64
➜  cifuzz git:(make-m1-mac) make build
go mod download
env GOOS=darwin GOARCH=arm64 go build -o build/bin/cifuzz_darwin cmd/cifuzz/main.go
➜  cifuzz git:(make-m1-mac) ./build/bin/cifuzz_darwin
Usage:
  cifuzz [command]

Available Commands:
  init        Set up a project for use with cifuzz
  create      Create a new fuzz test
  run         Build and run a fuzz test
  reload      Reload fuzz test metadata
  bundle      Bundles the fuzz test into an archive
  coverage    Generate a coverage report for a fuzz test
  finding     List and show findings
  help        Help about any command
  completion  Generate the autocompletion script for the specified shell

Flags:
  -C, --directory string   Change the directory before performing any operations
      --help               Show help for command
  -v, --verbose            Show more verbose output, can be helpful for debugging problems

Use "cifuzz [command] --help" for more information about a command.
```

**Review by adombeck — APPROVED** [review]

**Comment by fmeum** [comment]
Sorry, the merge is currently blocked because of an issue with our CI setup. I submitted https://github.com/CodeIntelligenceTesting/cifuzz/pull/238 to fix it.

**Comment by adombeck** [comment]
Thanks for your contribution, @MarkusZoppelt!

**Pull request merged**
