### PR TITLE
refactor: Simplify cmake include dir structure

### PR DESCRIPTION
**Pull request by florianGla**

### CODE REVIEW

**Comment by fmeum** [comment]
I just want to make sure it's an informed choice. I see the mild benefit of slightly simplifying the directory structure and the mild drawback that users get stuff on their include path that they shouldn't see. 

The decision can go either way and I'm fine with either. If this change allows for further simplifications down the line, that would be a clear argument in its favor.

**Comment by adombeck** [comment]
> I just want to make sure it's an informed choice. I see the mild benefit of slightly simplifying the directory structure and the mild drawback that users get stuff on their include path that they shouldn't see.

IIUC, with this change the user sees the following in their include path:
```
cifuzz/cifuzz.h
fuzzer/FuzzedDataProvider.h
legacy/fuzz_macro.h
```

Because `fuzz_macro.h` is below the `legacy` directory, it should be clear to users that they should not use this header unless they have legacy code which needs to use it (in which case they could either include it manually or use the `CIFUZZ_USE_DEPRECATED_MACROS` CMake variable to have it automatically included via the `-include` compiler flag). I don't really see an issue with that.

The benefit is that the horrible path
```
~/.local/share/cifuzz/share/include/cifuzz/cifuzz/cifuzz.h
```
becomes a little bit less horrible:
```
~/.local/share/cifuzz/share/include/cifuzz/cifuzz.h
```

@florianGla I think we could improve things a bit more by moving `~/.local/share/cifuzz/share/include` to `~/.local/share/cifuzz/include`. The `include` directory is usually not below `share`, see for example `ls /usr`. The same is true for `~/.local/share/cifuzz/share/src`.

**Comment by fmeum** [comment]
Convinved :⁠-⁠) Even more so with the suggested follow-up change.

**Review by fmeum — APPROVED** [review]

**Review by adombeck — APPROVED** [review]
@florianGla I will create a follow-up PR to move the `include` and `src` directories.

**Pull request merged**
