### PR TITLE
feat(gradle): print overridden jazzer version

### PR DESCRIPTION
**Pull request by bertschneider**
### Motivation/Context

We want to print a warning if the user manually sets the jazzer version and doesn't use the one provided by our maven extension. This can lead to unexpected issues.

### Description

Use new maven extension to detect jazzer versions.
Print warning in cifuzz, e.g. "Overriding default Jazzer version with version x.y.z".

### How to use/reproduce

Add the following snipped to the `build.gradle.kts` of our Gradle example project and start a fuzzing run.

```
dependencies {
  testImplementation("com.code-intelligence:jazzer-junit:0.21.1")
}
```

### CODE REVIEW

**Comment by MarkusZoppelt** [comment]
Did you use the updater script for aef8db60d2f3458d52691b699fe20338fd3b9770?

    go run tools/updater/updater.go --dependency gradle-plugin --version 1.11.0

**Review by MarkusZoppelt — APPROVED** [review]
I added 252497cbbb9c8f6a36dab32107a3e6ccc77b1975 that you can squash into aef8db60d2f3458d52691b699fe20338fd3b9770

**Comment by bertschneider** [comment]
> Did you use the updater script for [aef8db6](https://github.com/CodeIntelligenceTesting/cifuzz/commit/aef8db60d2f3458d52691b699fe20338fd3b9770)?
> 
> ```
> go run tools/updater/updater.go --dependency gradle-plugin --version 1.11.0
> ```

Ah, no, forgot about that tool. Thx for the fixup!

**Comment by bertschneider** [comment]
Oh, no! `automerge` was still active, even after failing jobs... @MarkusZoppelt, could you still take another look at the last commits?

**Pull request merged**
