### PR TITLE
Simplify install dir structure

### PR DESCRIPTION
**Pull request by florianGla**
This PR simplifies the directory structure of the cifuzz installation.

### CODE REVIEW

**Comment by florianGla** [comment]
I am not sure if the second commit is necessary. It changes the folder permissions of the completions folder to 0755, which is consistent with all other folders in the installation directory.

**Comment by florianGla** [comment]
Is it ok to use one general commit for all refactorings or do you prefer more specific commits and messages?

**Comment by adombeck** [comment]
> tools/cmake/cifuzz/share/CMakePresets.json → examples/cmake/CMakeUserPresets.json

Was this on purpose? If we want to add a `CMakeUserPresets.json` to our CMake example. lets do so in a separate commit.

**Comment by adombeck** [comment]
LGTM beside the one comment above.

We should create a follow-up ticket to also simplify the structure of paths like this: `~/.local/share/cifuzz/share/include/cifuzz/cifuzz/cifuzz.h`

**Comment by florianGla** [comment]
> > tools/cmake/cifuzz/share/CMakePresets.json → examples/cmake/CMakeUserPresets.json
> 
> Was this on purpose? If we want to add a `CMakeUserPresets.json` to our CMake example, lets do so in a separate commit.

No, that was an accident. Good catch.

**Pull request merged**
