### PR TITLE
feat(container): re-add `--registry` flag to remote-run

### PR DESCRIPTION
**Pull request by MarkusZoppelt**
### Motivation/Context

The `--registry` flag was indeed useful for playing around with `container remote-run`.
*Who would have thunk?*

### Description

Re-adds the `--registry` flag to the `container remote-run` cmd.
It uses the local docker credentials of the current user, so a `docker login` is needed first.

### How to use/reproduce

    az acr login --name cifuzzcontainers
    
    # or:
    docker login -u <your user> -p <your password> cifuzzcontainers.azurecr.io

    cifuzz container remote-run \
      -C examples/maven com.example.FuzzTestCase::myFuzzTest \
      --server app.staging.code-intelligence.com \
      --registry cifuzzcontainers.azurecr.io/cifuzz-dev/maven-example \
      -v

### CODE REVIEW

**Comment by florianGla** [comment]
Looks good to me. Your example does not work with CI Sense though. I guess this issue is unrelated to the `--registry` flag?

**Comment by MarkusZoppelt** [comment]
> Looks good to me. Your example does not work with CI Sense though. I guess this issue is unrelated to the `--registry` flag?

Yes, I guess it's because it does not have read access to cifuzzcontainers.azurecr.io, right @simonresch?

**Review by florianGla — APPROVED** [review]

**Comment by simonresch** [comment]
> > Looks good to me. Your example does not work with CI Sense though. I guess this issue is unrelated to the `--registry` flag?
> 
> Yes, I guess it's because it does not have read access to cifuzzcontainers.azurecr.io, right @simonresch?

CI Sense has read access to cifuzzcontainers.azurecr.io (the registry is public). What error are you getting? It's working fine for me.

**Comment by florianGla** [comment]
> CI Sense has read access to cifuzzcontainers.azurecr.io (the registry is public). What error are you getting? It's working fine for me.

The fuzzing run exited with status `incomplete` in CI Sense. Maybe this is an unrelated issue.

**Pull request merged**
