### PR TITLE
Add pre-push hook

### PR DESCRIPTION
**Pull request by adombeck**

### CODE REVIEW

**Comment by adombeck** [comment]
@jochil: I couldn't find a good YAML formatter to use here. In the core repo we use https://prettier.io/docs/en/install.html but I don't know if we want to depend on npm/yarn here.

**Comment by jochil** [comment]
> @jochil: I couldn't find a good YAML formatter to use here. In the core repo we use https://prettier.io/docs/en/install.html but I don't know if we want to depend on npm/yarn here.

I thought about that too... if prettier is the only npm package we would use, this might be overkill, especially for 3 yaml files.
If we add npm we can also use https://typicode.github.io/husky/ for the git hooks

**Comment by adombeck** [comment]
> If we add npm we can also use https://typicode.github.io/husky/ for the git hooks

Please not, husky was super annoying when we introduced it in the core repo

**Comment by jochil** [comment]
> > If we add npm we can also use https://typicode.github.io/husky/ for the git hooks
> 
> Please not, husky was super annoying when we introduced it in the core repo

So what's about running prettier only in the CI Pipeline? https://github.com/marketplace/actions/prettier-action

**Comment by adombeck** [comment]
> So what's about running prettier only in the CI Pipeline? https://github.com/marketplace/actions/prettier-action

A bit annoying when the pipeline fails because you didn't format your file the way we want but we don't provide the means to actually format the file that way, no?

**Comment by adombeck** [comment]
> I meant to actually format the file and commit the changes... during the pipeline

The CI automatically adding commits to your branch? I'm skeptical

**Comment by fmeum** [comment]
I also don't like pipelines modifying my commits. Have you taken a look at https://github.com/UltiRequiem/yamlfmt?

**Comment by jochil** [comment]
> > I meant to actually format the file and commit the changes... during the pipeline
> 
> The CI automatically adding commits to your branch? I'm skeptical

It can be done on the commit (amend) who changed the yaml file. But I agree... it can cause problems/confusion. Another option would be on the merge into main... 
I am not sure if this is worth the potential troubles

**Comment by adombeck** [comment]
> Have you taken a look at https://github.com/UltiRequiem/yamlfmt?

Yes, but same as `yq` - and in contrast to prettier - it removes empty lines which can help make the file more readable.

**Review by jochil — APPROVED** [review]

**Pull request merged**
