### PR TITLE
build/bazel: Fix UBSan C++ runtime not linked

### PR DESCRIPTION
**Pull request by adombeck**

### CODE REVIEW

**Review by fmeum — APPROVED** [review]

**Comment by adombeck** [comment]
I added a test

**Review by fmeum — APPROVED** [review]
@adombeck Looks good, but shouldn't the last two commits be switched? It seems as if the fix is coming after instead of before or with the test.

**Comment by fmeum** [comment]
@adombeck This is problematic with `git bisect` though. I agree that it is useful to verify that the test actually would have caught the issue and always do that locally, but would prefer the other order or a single squashed commit to keep the pipeline passing at every commit.

**Comment by adombeck** [comment]
> @adombeck This is problematic with git bisect though. I agree that it is useful to verify that the test actually would have caught the issue and always do that locally, but would prefer the other order or a single squashed commit to keep the pipeline passing at every commit.

Sorry, was about to rebase but apparently I accidentally merged the branch already :/

**Comment by fmeum** [comment]
> Sorry, was about to rebase but apparently I accidentally merged the branch already :/

Don't worry, it does not matter that much in the end. :-) We do have a fixup commit on main from an earlier PR merge, but I that's of course not a big deal as well.

**Comment by adombeck** [comment]
> We do have a fixup commit on main from an earlier PR merge, but I that's of course not a big deal as well.

Yeah, I also saw that and was annoyed about it, but I think force-pushing to main would cause more trouble than it would solve

**Comment by adombeck** [comment]
I wish it was possible to have a check in GitHub which avoids "WIP", "XXX" and "fixup" commits. I tried to add a test for that in CLI-676-check-wip-commits but there is no way to ignore this test for certain commits (sometimes we might actually do want commit messages with these strings in them).

**Comment by fmeum** [comment]
Could we restrict the check to commits that start with these terms? I don't see a situation in which we would want to merge such commits.

**Pull request merged**
