### PR TITLE
Link minijail statically

### PR DESCRIPTION
**Pull request by adombeck**

### CODE REVIEW

**Comment by florianGla** [comment]
I still get the following error: error while loading shared libraries: libcap.so.2: cannot open shared object file: No such file or directory

**Comment by adombeck** [comment]
> I still get the following error: error while loading shared libraries: libcap.so.2: cannot open shared object file: No such file or directory

Can you provide me the steps to reproduce?

**Comment by florianGla** [comment]
> > I still get the following error: error while loading shared libraries: libcap.so.2: cannot open shared object file: No such file or directory
> 
> Can you provide me the steps to reproduce?

I did something wrong, I'll try again

**Comment by adombeck** [comment]
Could you run this and then try again?
```
make -C third-party/minijail clean
```

**Comment by adombeck** [comment]
> RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/CodeIntelligenceTesting/cifuzz/CLI-447-static-minijail/install.sh)"

That downloads the latest release, it doesn't use an installer built from this branch

**Review by fmeum — APPROVED** [review]
Haven't tested this in Docker, but the changes LGTM.

**Review by jochil — CHANGES_REQUESTED** [review]
On my system I can not build the installer anymore with `make installer`. I get the following error:
```
go run tools/install/bundler/bundler.go --version dev 
go build -tags installer -o build/bin/cifuzz_installer_linux tools/install/installer/installer.go
rm -r tools/install/bundler/embed/bundle
Building cifuzz in /home/jochen/dev/workspace/ci/cifuzz/tools/install/bundler/embed/bundle
Command: /usr/sbin/make CC_BINARY(minijail0)
make[1]: Entering directory '/home/jochen/dev/workspace/ci/cifuzz/third-party/minijail'
Using BASE_VER=0
cd "/home/jochen/dev/workspace/ci/cifuzz/third-party/minijail/" && make -r -I "/home/jochen/dev/workspace/ci/cifuzz/third-party/minijail" -f "/home/jochen/dev/workspace/ci/cifuzz/third-party/minijail/Makefile" SRC="/home/jochen/dev/workspace/ci/cifuzz/third-party/minijail" OUT="/home/jochen/dev/workspace/ci/cifuzz/third-party/minijail/" "CC_BINARY(minijail0)"
make[2]: Entering directory '/home/jochen/dev/workspace/ci/cifuzz/third-party/minijail'
Using BASE_VER=0
build configuration:
- OUT=/home/jochen/dev/workspace/ci/cifuzz/third-party/minijail/
- SRC=/home/jochen/dev/workspace/ci/cifuzz/third-party/minijail
- MODE=opt
- SPLITDEBUG=0
- NOSTRIP=1
- VALGRIND=0
- COLOR=1
- CXXEXCEPTIONS=0
- ARCH=x86_64
- QEMU_ARCH=x86_64
- USE_QEMU=0
- NEEDS_ROOT=0
- NEEDS_MOUNTS=0
- SYSROOT=/

/home/jochen/dev/workspace/ci/cifuzz/third-party/minijail/Makefile:182: warning: overriding recipe for target 'libsyscalls.gen.pie.o'
common.mk:606: warning: ignoring old recipe for target 'libsyscalls.gen.pie.o'
/home/jochen/dev/workspace/ci/cifuzz/third-party/minijail/Makefile:182: warning: overriding recipe for target 'libsyscalls.gen.pic.o'
common.mk:606: warning: ignoring old recipe for target 'libsyscalls.gen.pic.o'
/home/jochen/dev/workspace/ci/cifuzz/third-party/minijail/Makefile:182: warning: overriding recipe for target 'libsyscalls.gen.o.depends'
common.mk:606: warning: ignoring old recipe for target 'libsyscalls.gen.o.depends'
/home/jochen/dev/workspace/ci/cifuzz/third-party/minijail/Makefile:182: warning: overriding recipe for target 'libsyscalls.gen.o'
common.mk:606: warning: ignoring old recipe for target 'libsyscalls.gen.o'
/home/jochen/dev/workspace/ci/cifuzz/third-party/minijail/Makefile:196: warning: overriding recipe for target 'libconstants.gen.pie.o'
common.mk:606: warning: ignoring old recipe for target 'libconstants.gen.pie.o'
/home/jochen/dev/workspace/ci/cifuzz/third-party/minijail/Makefile:196: warning: overriding recipe for target 'libconstants.gen.pic.o'
common.mk:606: warning: ignoring old recipe for target 'libconstants.gen.pic.o'
/home/jochen/dev/workspace/ci/cifuzz/third-party/minijail/Makefile:196: warning: overriding recipe for target 'libconstants.gen.o.depends'
common.mk:606: warning: ignoring old recipe for target 'libconstants.gen.o.depends'
/home/jochen/dev/workspace/ci/cifuzz/third-party/minijail/Makefile:196: warning: overriding recipe for target 'libconstants.gen.o'
common.mk:606: warning: ignoring old recipe for target 'libconstants.gen.o'
LDCC		minijail0
/usr/sbin/ld: cannot find -lcap: No such file or directory
/usr/sbin/ld: minijail0.pie.o: in function `main':
/home/jochen/dev/workspace/ci/cifuzz/third-party/minijail/minijail0.c:59: warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/sbin/ld: libminijail.pie.o: in function `drop_ugid':
/home/jochen/dev/workspace/ci/cifuzz/third-party/minijail/libminijail.c:1983: warning: Using 'initgroups' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/sbin/ld: system.pie.o: in function `lookup_group':
/home/jochen/dev/workspace/ci/cifuzz/third-party/minijail/system.c:454: warning: Using 'getgrnam_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/sbin/ld: system.pie.o: in function `lookup_user':
/home/jochen/dev/workspace/ci/cifuzz/third-party/minijail/system.c:405: warning: Using 'getpwnam_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
collect2: error: ld returned 1 exit status
make[2]: *** [common.mk:479: CC_BINARY(minijail0)] Error 1
make[2]: Leaving directory '/home/jochen/dev/workspace/ci/cifuzz/third-party/minijail'
make[1]: *** [common.mk:172: CC_BINARY(minijail0)] Error 2
make[1]: Leaving directory '/home/jochen/dev/workspace/ci/cifuzz/third-party/minijail'
❌ exit status 2
exit status 1
tools/install/bundler/embed/embed_bundle.go:11:12: pattern bundle: cannot embed directory bundle: contains no embeddable files
```

**Comment by florianGla** [comment]
libminijail[92]: clone(CLONE_NEWPID | ...) failed with EPERM; is this process missing CAP_SYS_ADMIN?: Operation not permitted

steps to reproduce: 
FROM ubuntu:22.04
ENV TZ=Europe/Berlin
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt update
RUN apt install -y cmake llvm-11 clang-11 git golang-go make libcap-dev
# install other requirements
RUN apt install -y subversion curl
RUN ln -s /usr/bin/clang-11 /usr/bin/clang
RUN ln -s /usr/bin/clang++-11 /usr/bin/clang++
RUN ln -s /usr/bin/llvm-symbolizer-11 /usr/bin/llvm-symbolizer
RUN git clone https://github.com/CodeIntelligenceTesting/cifuzz.git
WORKDIR cifuzz
RUN go run tools/install/bundler/bundler.go --version dev
RUN go run -tags installer tools/install/installer/installer.go
RUN apt purge libcap-dev -y
WORKDIR examples/cmake
RUN git checkout CLI-447-static-minijail
RUN ~/cifuzz/bin/cifuzz --version
RUN ~/cifuzz/bin/cifuzz run my_fuzz_test

**Comment by fmeum** [comment]
@adombeck Thinking about it some more and seeing @jochil's compilation output, maybe we shouldn't use `-static`? This links in glibc statically [with all the issues this may cause](https://stackoverflow.com/a/57478728/297261). Which libraries are we using besides glibc that we would want to link in statically?

**Comment by florianGla** [comment]
I got the following error in docker:

libminijail[92]: clone(CLONE_NEWPID | ...) failed with EPERM; is this process missing CAP_SYS_ADMIN?: Operation not permitted

steps to reproduces:

FROM ubuntu:22.04
ENV TZ=Europe/Berlin
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt update
RUN apt install -y cmake llvm-11 clang-11 git golang-go make libcap-dev
RUN apt install -y subversion curl
RUN ln -s /usr/bin/clang-11 /usr/bin/clang
RUN ln -s /usr/bin/clang++-11 /usr/bin/clang++
RUN ln -s /usr/bin/llvm-symbolizer-11 /usr/bin/llvm-symbolizer
RUN git clone https://github.com/CodeIntelligenceTesting/cifuzz.git
WORKDIR cifuzz
RUN git checkout CLI-447-static-minijail
RUN go run tools/install/bundler/bundler.go --version dev
RUN go run -tags installer tools/install/installer/installer.go
RUN apt purge libcap-dev -y
WORKDIR examples/cmake
RUN ~/cifuzz/bin/cifuzz --version
RUN ~/cifuzz/bin/cifuzz run my_fuzz_test

**Comment by adombeck** [comment]
> I got the following error in docker:
> 
> libminijail[92]: clone(CLONE_NEWPID | ...) failed with EPERM; is this process missing CAP_SYS_ADMIN?: Operation not permitted

That looks like you were able to execute the minijail executable and ran into another issue (minijail requiring `CAP_SYS_ADMIN`, which means you need to start the Docker container with `--privileged`).

**Comment by adombeck** [comment]
> @adombeck Thinking about it some more and seeing @jochil's compilation output, maybe we shouldn't use -static? This links in glibc statically [with all the issues this may cause](https://stackoverflow.com/a/57478728/297261).

Right. 

> Which libraries are we using besides glibc that we would want to link in statically?

I think we only want to link libcap statically:
```
$ ldd minijail0
	linux-vdso.so.1 (0x00007ffc3569b000)
	libcap.so.2 => /lib/x86_64-linux-gnu/libcap.so.2 (0x00007f5291880000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f5291600000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f52918e7000)
```

**Comment by adombeck** [comment]
> We should be able to pull that off with -l:libcap.a added to the linker commandline.

That doesn't seem to work:

```
cd third-party/minijail && make clean && LDFLAGS="-l:libcap.a" make 'CC_BINARY(minijail0)' && ldd minijail0
[...]
	linux-vdso.so.1 (0x00007ffc029e7000)
	libcap.so.2 => /lib/x86_64-linux-gnu/libcap.so.2 (0x00007f3691ed5000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f3691c00000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f3691f3c000)
```

**Comment by fmeum** [comment]
> > We should be able to pull that off with -l:libcap.a added to the linker commandline.
> 
> That doesn't seem to work:
> 
> ```
> cd third-party/minijail && make clean && LDFLAGS="-l:libcap.a" make 'CC_BINARY(minijail0)' && ldd minijail0
> [...]
> 	linux-vdso.so.1 (0x00007ffc029e7000)
> 	libcap.so.2 => /lib/x86_64-linux-gnu/libcap.so.2 (0x00007f3691ed5000)
> 	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f3691c00000)
> 	/lib64/ld-linux-x86-64.so.2 (0x00007f3691f3c000)
> ```

Where is libcap.a coming from with `-static`? It's possible that the order of the LDFLAGS is wrong or maybe its not on the search path. We can take a look together.

**Comment by adombeck** [comment]
This seems to work:
```
make clean && LDFLAGS="-Wl,-Bstatic -lcap -Wl,-Bdynamic" make 'CC_BINARY(minijail0)' && ldd minijail0
[...]
	linux-vdso.so.1 (0x00007ffeee9ca000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f6aa7800000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f6aa7a91000)
```

**Comment by adombeck** [comment]
I pushed a new commit which on my system produces a `minijail0` binary with `libcap` linked statically and all other libraries linked dynamically.

**Comment by fmeum** [comment]
That's the canonical way to do it, so if it works for us and in CI, I would say it's correct.

**Comment by jochil** [comment]
I checked again and I am still getting this error:
```
LDCC		minijail0
/usr/sbin/ld: cannot find -lcap: No such file or directory
/usr/sbin/ld: minijail0.pie.o: in function `main':
/home/jochen/dev/workspace/ci/cifuzz/third-party/minijail/minijail0.c:59: warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/sbin/ld: libminijail.pie.o: in function `drop_ugid':
/home/jochen/dev/workspace/ci/cifuzz/third-party/minijail/libminijail.c:1983: warning: Using 'initgroups' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/sbin/ld: system.pie.o: in function `lookup_group':
/home/jochen/dev/workspace/ci/cifuzz/third-party/minijail/system.c:454: warning: Using 'getgrnam_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/sbin/ld: system.pie.o: in function `lookup_user':
/home/jochen/dev/workspace/ci/cifuzz/third-party/minijail/system.c:405: warning: Using 'getpwnam_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
collect2: error: ld returned 1 exit status
make[2]: *** [common.mk:479: CC_BINARY(minijail0)] Error 1
make[2]: Leaving directory '/home/jochen/dev/workspace/ci/cifuzz/third-party/minijail'
make[1]: *** [common.mk:172: CC_BINARY(minijail0)] Error 2
make[1]: Leaving directory '/home/jochen/dev/workspace/ci/cifuzz/third-party/minijail'
❌ exit status 2
exit status 1
```
libcap is available, as it was found with the dynamic linked lib from the installer
```
ldd minijail0
	linux-vdso.so.1 => linux-vdso.so.1 (0x00007fffac767000)
	libcap.so.2 => /usr/lib/libcap.so.2 (0x00007fe617390000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007fe6171a9000)
	/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007fe6173fa000)
```
Any idea what else to check?

**Comment by fmeum** [comment]
It's possible that your image doesn't contain `libcap.a` - we probably have to add `libcap-dev` to our requirements in `CONTRIBUTING.md`.

**Comment by jochil** [comment]
> It's possible that your image doesn't contain `libcap.a` - we probably have to add `libcap-dev` to our requirements in `CONTRIBUTING.md`.

sorry for not pointing out... but this is not a docker image. It is my actual system and libcap is installed

**Comment by fmeum** [comment]
But is `libcap-dev` also installed? Which system are you using and which of its packages contains `libcap.a`?

**Comment by jochil** [comment]
> But is `libcap-dev` also installed? Which system are you using and which of its packages contains `libcap.a`?

I investigated a little bit together with @adombeck. My system is Arch based and there is no `libcap-dev` available, only `libcap` (https://archlinux.org/packages/core/x86_64/libcap/).. which is ok, but it seems like it is not common for Arch to distribute static linked libraries.

**Review by jochil — APPROVED** [review]

**Comment by jochil** [comment]
As this affects only users building the installer from source we can just put a hint + instructions in the `CONTRIBUTING.md`. I will do the same for my system

**Comment by adombeck** [comment]
I added this change as a patch and changed the `update.sh` script to apply that patch.

**Pull request merged**
