### PR TITLE
Check ErrSilent during coverage test

### PR DESCRIPTION
**Pull request by MarkusZoppelt**
This generates and opens a coverage report even if `runFuzzTest(buildResult)` returns a silent error.

**Example (example/cmake fails on Mac arm64):**
```
Building my_fuzz_test
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/mz/code/cifuzz/examples/cmake/.cifuzz-build/replayer/coverage
Consolidate compiler generated dependencies of target exploreMe
[ 40%] Built target exploreMe
Consolidate compiler generated dependencies of target my_fuzz_test
[100%] Built target my_fuzz_test
Running my_fuzz_test on corpus
❌ my_fuzz_test: exit status 1

✅ Coverage Report:
              File | Functions Hit/Found |  Lines Hit/Found | Branches Hit/Found
  my_fuzz_test.cpp |      2 / 2 (100.0%) |   8 / 8 (100.0%) |     0 / 0 (100.0%)
src/explore_me.cpp |      1 / 1 (100.0%) | 19 / 21  (90.5%) |     4 / 8  (50.0%)
                   |                     |                  |                   
                   | Functions Hit/Found |  Lines Hit/Found | Branches Hit/Found
             Total |               3 / 3 |          27 / 29 |              4 / 8

```

IMHO this is a more helpful behaviour compared to only logging an `exit status 1` message.

### CODE REVIEW

**Comment by jochil** [comment]
IMO this is useful... @fmeum @adombeck @HenrichN what do you think?
I might happen that the coverage numbers are lower than expected, but as long as it is clear that the run failed unexpectedly I think it is ok showing them

@MarkusZoppelt thanks for the PR!
Do you have an actual example to look at? I would be interested to see how much of the coverage report got generated/exported and what was the reason for the crash.

**Comment by MarkusZoppelt** [comment]
> Do you have an actual example to look at? I would be interested to see how much of the coverage report got generated/exported and what was the reason for the crash.

Sure, below is the output of the **untouched** cmake example with my fix.

Generated html report:
https://gist.github.com/MarkusZoppelt/be8314043bf98bbc81a6c205317d9aa1

Command log:
```
~/x/cifuzz > make build
go mod download
env GOOS=darwin GOARCH=arm64 go build -o build/bin/cifuzz_darwin cmd/cifuzz/main.go
~/x/cifuzz > cd examples/cmake       
~/x/cifuzz/examples/cmake > ../../build/bin/cifuzz_darwin run my_fuzz_test 
-- The C compiler identification is Clang 14.0.6
-- The CXX compiler identification is Clang 14.0.6
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /opt/homebrew/opt/llvm/bin/clang - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /opt/homebrew/opt/llvm/bin/clang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/mz/x/cifuzz/examples/cmake/.cifuzz-build/libfuzzer/address+undefined
[ 20%] Building CXX object src/CMakeFiles/exploreMe.dir/explore_me.cpp.o
[ 40%] Linking CXX static library libexploreMe.a
[ 40%] Built target exploreMe
[ 60%] Building CXX object CMakeFiles/my_fuzz_test.dir/my_fuzz_test.cpp.o
[ 80%] Building C object CMakeFiles/my_fuzz_test.dir/Users/mz/cifuzz/share/cifuzz/src/launcher.c.o
[100%] Linking CXX executable my_fuzz_test
[100%] Built target my_fuzz_test
Running my_fuzz_test                                                                                       
Storing generated corpus in .cifuzz-corpus/my_fuzz_test                                                    
Starting from an empty corpus                                                                              
                                                                                                           
================= Finding 1 [unruffled_panini] ==================
heap-buffer-overflow on address 0x000109e54031 at pc 0x000100bb19a8 bp 0x00016f8c2bb0 sp 0x00016f8c2370    
in exploreMe (src/explore_me.cpp:24:11)                                                                    
                                                                                                           
Further details:

    cifuzz finding unruffled_panini
                                                                                                           
Note: The crashing input has been copied to the seed corpus at:

    my_fuzz_test_seed_corpus/unruffled_panini-1

It will now be used as a seed input for all runs of the fuzz test,
including remote runs with artifacts created via 'cifuzz bundle' and
regression tests. For more information on regression tests, see:

    https://github.com/CodeIntelligenceTesting/cifuzz#regression-testing

=================================================================                                          

Execution time: 2s                                                                                         
Average exec/s: 394107                                                                                     
Findings:       1                                                                                          
New seeds:      37 (total: 37)                                                                             
~/x/cifuzz/examples/cmake > ../../build/bin/cifuzz_darwin coverage my_fuzz_test
Building my_fuzz_test
-- The C compiler identification is Clang 14.0.6
-- The CXX compiler identification is Clang 14.0.6
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /opt/homebrew/opt/llvm/bin/clang - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /opt/homebrew/opt/llvm/bin/clang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/mz/x/cifuzz/examples/cmake/.cifuzz-build/replayer/coverage
[ 20%] Building CXX object src/CMakeFiles/exploreMe.dir/explore_me.cpp.o
[ 40%] Linking CXX static library libexploreMe.a
[ 40%] Built target exploreMe
[ 60%] Building CXX object CMakeFiles/my_fuzz_test.dir/my_fuzz_test.cpp.o
[ 80%] Building C object CMakeFiles/my_fuzz_test.dir/Users/mz/cifuzz/share/cifuzz/src/replayer.c.o
[100%] Linking CXX executable my_fuzz_test
[100%] Built target my_fuzz_test
Running my_fuzz_test on corpus
❌ my_fuzz_test: exit status 1

✅ Coverage Report:
              File | Functions Hit/Found |  Lines Hit/Found | Branches Hit/Found
  my_fuzz_test.cpp |      2 / 2 (100.0%) |   8 / 8 (100.0%) |     0 / 0 (100.0%)
src/explore_me.cpp |      1 / 1 (100.0%) | 19 / 21  (90.5%) |     4 / 8  (50.0%)
                   |                     |                  |                   
                   | Functions Hit/Found |  Lines Hit/Found | Branches Hit/Found
             Total |               3 / 3 |          27 / 29 |              4 / 8

```

**Comment by adombeck** [comment]
I'm not sure in which error case we would want to still show the incomplete report.

> Sure, below is the output of the untouched cmake example with my fix.
> [...]

Creating a coverage report for the cmake example should not fail, so something is broken. I can't reproduce this on my system, maybe this has something to do with the arm64 macOS platform you're using. 

There is another issue here: If the fuzzer fails, we should print its stderr to allow the users (and us) to figure out what's wrong. I implemented that on https://github.com/CodeIntelligenceTesting/cifuzz/pull/256. @MarkusZoppelt, could you try the `cifuzz coverage` command again on that branch? That will hopefully provide a more useful error message.

**Comment by MarkusZoppelt** [comment]
> Creating a coverage report for the cmake example should not fail, so something is broken.

That's what I thought, too.

Here's the error when running coverage from #256:

```
~/code/cifuzz/examples/cmake > ../../build/bin/cifuzz_darwin coverage my_fuzz_test
Building my_fuzz_test
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/mz/code/cifuzz/examples/cmake/.cifuzz-build/replayer/coverage
Consolidate compiler generated dependencies of target exploreMe
[ 40%] Built target exploreMe
Consolidate compiler generated dependencies of target my_fuzz_test
[100%] Built target my_fuzz_test
Running my_fuzz_test on corpus
Running: /Users/mz/code/cifuzz/examples/cmake/my_fuzz_test_seed_corpus/gracious_curie
Done:    /Users/mz/code/cifuzz/examples/cmake/my_fuzz_test_seed_corpus/gracious_curie: (15 bytes)
Running: /Users/mz/code/cifuzz/examples/cmake/my_fuzz_test_seed_corpus/unruffled_panini-1
Done:    /Users/mz/code/cifuzz/examples/cmake/my_fuzz_test_seed_corpus/unruffled_panini-1: (15 bytes)
Failed to list files in '/Users/mz/code/cifuzz/examples/cmake/my_fuzz_test_seed_corpus': Inappropriate ioctl for device

Fuzz test failed on input ' +_E'
Reason: Fuzz target exited


❌ my_fuzz_test: exit status 1
```

**Comment by adombeck** [comment]
> Here's the error when running coverage from https://github.com/CodeIntelligenceTesting/cifuzz/pull/256:

Thanks! So apparently the replayer is broken on your system. We should add a test for arm64 macOS. I will create a ticket for that and discuss it in the team.

**Comment by jochil** [comment]
> Creating a coverage report for the cmake example should not fail

For the cmake example this is definitely true und this is why I asked for an example of a crashing coverage report.

But in general a coverage report can legitimately fail, or? For example, when we have an input that causes a crash without sanitizer (seg fault, division by null, ...)

**Comment by adombeck** [comment]
> But in general a coverage report can legitimately fail, or? For example, when we have an input that causes a crash without sanitizer (seg fault, division by null, ...)

Yes, and we should think about how we want to handle that case. Creating an incomplete coverage report might be better than producing no coverage report at all, but I think what we actually want is to start the replayer again and let it feed in the remaining inputs.

**Comment by jochil** [comment]
@MarkusZoppelt FYI we scheduled an internal meeting for the next week to discuss "crash resisting coverage reports" in general... we will put this PR on hold until then.

**Comment by jochil** [comment]
@MarkusZoppelt we work internally on a more "general" solution... so I will close this PR. See you soon :wink:

**Comment by jochil** [comment]
> Will this solution also fix the broken replayer on macOS arm64?

No but we created another internal task targeting this problem

> Shall I create a separate issue?

Feel free to do so if you want to work on it, that would be very welcomed of course :slightly_smiling_face:

**Comment by MarkusZoppelt** [comment]
> I tried debugging it some more, but I couldn't figure out why the replayer fails on macOS arm64 for the example... somehow the syscall for ioctl fails.

Seems the issue is fixed now.

Just tested on commit 77405c44281f14f1f2bacaeacece7e34a0be9d8b and `examples/cmake` and `examples/other` work without issues (i.e. _run_ and _coverage_)

**Comment by jochil** [comment]
Thanks for testing it again. We did not intentionally fix it, maybe it was a side effect of another task :)
We will take a look

**Pull request closed without merging**
