### PR TITLE
chore: Update Jazzer to 0.21.1

### PR DESCRIPTION
**Pull request by adombeck**
### Motivation/Context

New Jazzer version

### Description

Closes CLI-1296

### CODE REVIEW

**Review by MarkusZoppelt — APPROVED** [review]

**Comment by MarkusZoppelt** [comment]
Will this need some commits from #1073?

**Comment by adombeck** [comment]
> Will this need some commits from #1073?

I'm not sure, I'm waiting for the test results. If they pass, I assume we can merge as is and @florianGla can cherry-pick the fix commits from #1073 to another branch and create a new PR.

**Comment by florianGla** [comment]
I'm surprised if the integration tests run successful. You could cherry pick my commits regarding the JUnit issue if you like.

**Comment by adombeck** [comment]
@florianGla thanks for the update to 0.21.1. 

> I'm surprised if the integration tests run successfully. You could cherry pick my commits regarding the JUnit issue if you like.

Looks like they did pass. I'm gonna merge this now so that the backend team is unblocked. Maybe you can cherry-pick these commits to another branch.

**Pull request merged**
