### PR TITLE
build: Add -I for cifuzz.h in coverage builds

### PR DESCRIPTION
**Pull request by fmeum**
Achieved by moving the FUZZ_TEST_CFLAGS logic into the common build env.

### CODE REVIEW

**Comment by fmeum** [comment]
@pnoltof

**Comment by pnoltof** [comment]
That works!
Thanks for the quick fix!

**Comment by fmeum** [comment]
Switching to draft as `CommonBuildEnv` is also used in CMake.

**Comment by fmeum** [comment]
Fixed by duplicating the include path logic. That's probably the better approach anyway as it protects us from overwriting the variable without noticing.

**Review by jochil — APPROVED** [review]

**Pull request merged**
