### PR TITLE
Add email contact and docs link to issue template

### PR DESCRIPTION
**Pull request by JackuB**
This PR is a part of our work on introducing a more defined contribution model for external users.

Using GH's issue config file: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

However, `mailto:` links are not allowed, but you can get around with a link shortener.

### CODE REVIEW

**Comment by jochil** [comment]
> However, mailto: links are not allowed, but you can get around with a link shortener.

Can you add this as a comment in the yml file, too?

**Review by MarkusZoppelt — CHANGES_REQUESTED** [review]
```
    url: https://tinyurl.com/nkxuwh9v
```

Link shorteners leave a very bad taste in my mouth.
Users cannot see where the link is ultimately going.

I would rather have the email link not clickable than a shortener link.

**Comment by JackuB** [comment]
> I would rather have the email link not clickable than a shortener link.

That is pretty much the state. Text in the issue contains the email, user is able to copy-paste it and not click the link.

**Review by jochil — APPROVED** [review]

**Review by MarkusZoppelt — APPROVED** [review]

**Comment by Marcono1234** [comment]
Are GitHub issues not supposed to be used at all for this repository, not even for bug reports? Because that is what the issue templates and the README might currently suggest.

Using e-mail seems quite inconvenient and non-transparent for reporting issues to me. And I would assume you will also get duplicate reports because there is no way for users to search for existing reports.

**Pull request merged**
